### ISSUE TITLE
Threading issue when using LifestyleScoped

### ISSUE THREAD

**Issue by robertturner** [castleproject/Windsor#103]
I am getting an internal exception in when resolving using LifestyleScoped in a multi-threaded app.
I'm resolving instances via factories which call a scoped accessor. The exception doesn't occur in the accessor but when attempting to set the Burden. I get the following ArgumentException: "An item with the same key has already been added." with stack trace:

```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Castle.MicroKernel.Lifestyle.Scoped.ScopeCache.set_Item(Object id, Burden value)
   at Castle.MicroKernel.Lifestyle.Scoped.DefaultLifetimeScope.GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, IDictionary additionalArguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
   at Castle.Facilities.TypedFactory.TypedFactoryComponentResolver.Resolve(IKernelInternal kernel, IReleasePolicy scope)
   at Castle.Facilities.TypedFactory.Internal.TypedFactoryInterceptor.Resolve(IInvocation invocation)
   at Castle.Facilities.TypedFactory.Internal.TypedFactoryInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IPSECommonIOFactoryProxy.Create(IFtpObj ftpObj)
```

My scoped accessor is pretty benign and doesn't throw any exceptions. For reference the code is:

```
public class ArgScopeAccessor : IScopeAccessor
{
    static readonly ConcurrentDictionary<object, ILifetimeScope> collection = new ConcurrentDictionary<object, ILifetimeScope>();

    public void Dispose()
    {
        foreach (var scope in collection)
            scope.Value.Dispose();
        collection.Clear();
    }

    public ILifetimeScope GetScope(CreationContext context)
    {
        if (context.AdditionalArguments.Count != 1)
            throw new ArgumentException("Expect one and only one argument");
        object arg = null;
        foreach (var a in context.AdditionalArguments.Values)
            arg = a;

        return collection.GetOrAdd(arg, n => new DefaultLifetimeScope());
    }
}
```

**Comment by jonorossi** [comment]
I know this is a really old issue, however it is [explicitly called out in the documentation](https://github.com/castleproject/Windsor/blob/master/docs/implementing-custom-scope.md#the-scope-abstraction-ilifetimescope) that `DefaultLifetimeScope` is not thread safe and the docs provide an example of implementing a scope that is. This is a conscience design decision.

`DefaultLifetimeScope` is used by many lifestyles that don't need multi-threaded scope resolution (and don't want the performance hit of synchronisation) including the PerWebRequest lifestyle where execution happens on a single thread.

#221 includes additional info where this issue has come up again with another custom lifestyle.
