### ISSUE TITLE
Mismatched async methods

### ISSUE THREAD

**Issue by Brandonjknox** [castleproject/Windsor#111]
We have been running into an issue when our application is first initializing after a deploy. It is thought that it is an issue when windsor is initializing the wcf services. This happens sparitically and only after  a deployment. 

The synchronous OperationContract method 'GetNamedUrls' in type 'INamedSvc' was matched with the asynchronous OperationContract methods 'BeginGetNamedUrlsUrls' and 'EndDelete' because they have the same operation name 'GetNamedUrls'. When a synchronous OperationContract method is matched to a pair of asynchronous OperationContract methods, the two OperationContracts must define the same return type. In this case, the return types are different. To fix it, ensure that method 'GetNamedUrls' and method 'EndDelete' have the same return type. Alternatively, changing the name of one of the methods will prevent matching. 
   at System.ServiceModel.Description.TypeLoader.SyncAsyncOperationConsistencyVerifier.VerifyReturnType()
   at System.ServiceModel.Description.TypeLoader.VerifyConsistency(OperationConsistencyVerifier verifier)
   at System.ServiceModel.Description.TypeLoader.CreateOperationDescription(ContractDescription contractDescription, MethodInfo methodInfo, MessageDirection direction, ContractReflectionInfo reflectionInfo, ContractDescription declaringContract)
   at System.ServiceModel.Description.TypeLoader.CreateOperationDescriptions(ContractDescription contractDescription, ContractReflectionInfo reflectionInfo, Type contractToGetMethodsFrom, ContractDescription declaringContract, MessageDirection direction)
   at System.ServiceModel.Description.TypeLoader.CreateContractDescription(ServiceContractAttribute contractAttr, Type contractType, Type serviceType, ContractReflectionInfo& reflectionInfo, Object serviceImplementation)
   at System.ServiceModel.Description.TypeLoader.LoadContractDescriptionHelper(Type contractType, Type serviceType, Object serviceImplementation)
   at System.ServiceModel.ChannelFactory`1.CreateDescription()
   at Castle.Proxies.Invocations.ChannelFactory`1_CreateDescription_3.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ChannelFactory`1Proxy_3.CreateDescription()
   at System.ServiceModel.ChannelFactory.InitializeEndpoint(String configurationName, EndpointAddress address)
   at System.ServiceModel.ChannelFactory`1..ctor(String endpointConfigurationName, EndpointAddress remoteAddress)

**Comment by queil** [comment]
I am also experiencing this bug. It appears mostly in multi-threaded scenarios. In one of our services when it spins up after a release and gets hit by multiple requests at once. It also started appearing recently in a test environment once we parallelised our tests. I believe it must be a bug in WcfFacility.

**Comment by hammett** [comment]
So it seems the issue is within the WCF facility. I dont think anyone is actively maintaining it. I personally have never used it. Your best course of action here is to submit a PR.

**Comment by queil** [comment]
I've looked into that closer and it seems only occurring when a service contract only has synchronous operations and it's used with DefaultClientModel (with WantsAsyncCapability == true by default) and only when CreateChannelFactory runs in parallel (it seems to depend on the number of  methods in the contract, some contracts would fail with just 10 parallel executions, shorter ones with more, so it is dependent on a particular environment). The bug stops appearing once ChannelFactory gets cached.

The work-around for sync-only contracts it to use the following registration:
`Component.For<IOperations>().AsWcfClient(new DefaultClientModel().WithoutAsyncCapability()`
 
For async-only and mixed contracts this bug does not seem to occur.

**Comment by hammett** [comment]
My suspicion is more towards the ordering of members returned by Reflection operations. If it happens to return the Task based ones before the other, you'll get the error. An appropriate if (typeof(Task).IsAssignableFrom(returnType)) will fix it -- if my suspicion is correct.

**Comment by queil** [comment]
Sorry, I am not necessarily sure what you're referring to. Can you please elaborate? I do not have any Task based methods.

**Comment by hammett** [comment]
I'm guiding myself by this:

> The synchronous OperationContract method 'GetBankRefreshGroup' in type 'XXXXXX.Core.Interfaces.Services.Ixxxxxxxxxxxxx' was matched with the asynchronous OperationContract methods 'BeginGetBankRefreshGroup' and 'EndGetPersonCurrentBank' because they have the same operation name 'GetBankRefreshGroup'. When a synchronous OperationContract method is matched to a pair of asynchronous OperationContract methods, the two OperationContracts must define the same return type. In this case, the return types are different. To fix it, ensure that method 'GetBankRefreshGroup' and method 'EndGetPersonCurrentBank' have the same return type

Who's doing this "match"?

**Comment by queil** [comment]
Please have a look in the CreateDescriptionInterceptor class in [this file](https://github.com/castleproject/Windsor/blob/36c8ff8e2ac29de328e9a6915bb6eb275592cfda/src/Castle.Facilities.WcfIntegration/Client/Async/AsyncChannelFactoryBuilder.cs). It intercepts ChannelFactory.CreateDescription() and hacks-on some fake async methods using [AsyncType](https://github.com/castleproject/Windsor/blob/36c8ff8e2ac29de328e9a6915bb6eb275592cfda/src/Castle.Facilities.WcfIntegration/Client/Async/TypeSystem/AsyncType.cs) class and its CollectAsynchronousMethods method. Then it blows up (in circumstances described above) on generating ChannelFactory proxy when passed down to ServiceModel classes where it gets processed:

> 

> System.ServiceModel.Description.TypeLoader.SyncAsyncOperationConsistencyVerifier.VerifyReturnType()
>    at System.ServiceModel.Description.TypeLoader.VerifyConsistency(OperationConsistencyVerifier verifier)
>    at System.ServiceModel.Description.TypeLoader.CreateOperationDescription(ContractDescription contractDescription, MethodInfo methodInfo, MessageDirection direction, ContractReflectionInfo reflectionInfo, ContractDescription declaringContract)
>    at System.ServiceModel.Description.TypeLoader.CreateOperationDescriptions(ContractDescription contractDescription, ContractReflectionInfo reflectionInfo, Type contractToGetMethodsFrom, ContractDescription declaringContract, MessageDirection direction)

**Comment by hammett** [comment]
bear in mind I've never used WCF.

The CollectAsynchronousMethods is suspicious. Could you paste there the public api of the class containing GetBankRefreshGroup?

**Comment by queil** [comment]
Well, not necessarily as this is confidential but I was able to replicate this with [IOperations](https://github.com/castleproject/Windsor/blob/36c8ff8e2ac29de328e9a6915bb6eb275592cfda/src/Castle.Facilities.WcfIntegration.Tests/Components/IOperations.cs). Please have a look at the following (IOperationsAll and IAsyncOperations are also in the above file):

 ```
 [Test]
        public void Will_throw_sync_only_contract()
        {
            var builder = new AsynChannelFactoryBuilder<DefaultClientModel>(new ProxyGenerator());
            Parallel.For(0, 1000, x => builder.CreateChannelFactory<ChannelFactory<IOperations>>(new DefaultClientModel()));
        }

        [Test]
        public void Will_not_throw_no_async_capability()
        {
            var builder = new AsynChannelFactoryBuilder<DefaultClientModel>(new ProxyGenerator());
            Parallel.For(0, 1000, x => builder.CreateChannelFactory<ChannelFactory<IOperations>>(new DefaultClientModel().WithoutAsyncCapability()));
        }

        [Test]
        public void Will_not_throw_mixed_contract()
        {
            var builder = new AsynChannelFactoryBuilder<DefaultClientModel>(new ProxyGenerator());
            Parallel.For(0, 1000, x => builder.CreateChannelFactory<ChannelFactory<IOperationsAll>>(new DefaultClientModel()));
        }

        [Test]
        public void Will_not_throw_async_only_contract()
        {
            var builder = new AsynChannelFactoryBuilder<DefaultClientModel>(new ProxyGenerator());
            Parallel.For(0, 1000, x => builder.CreateChannelFactory<ChannelFactory<IAsyncOperations>>(new DefaultClientModel()));
        } 
```

**Comment by hammett** [comment]
Thanks for creating a repro. Right now I cant really look further. I'll see
if I get some spare time during this week.

On Sun, Jun 19, 2016 at 5:23 PM, queil <notifications@github.com> wrote:

> Well, not necessarily as this is confidential but I was able to replicate
> this with IOperations
> <https://github.com/castleproject/Windsor/blob/36c8ff8e2ac29de328e9a6915bb6eb275592cfda/src/Castle.Facilities.WcfIntegration.Tests/Components/IOperations.cs>.
> Please have a look at the following (IOperationsAll and IAsyncOperations
> are also in the above file):
>
>  [Test]
>         public void Will_throw_sync_only_contract()
>         {
>             var builder = new AsynChannelFactoryBuilder<DefaultClientModel>(new ProxyGenerator());
>             Parallel.For(0, 1000, x => builder.CreateChannelFactory<ChannelFactory<IOperations>>(new DefaultClientModel()));
>         }
>
>         [Test]
>         public void Will_not_throw_no_async_capability()
>         {
>             var builder = new AsynChannelFactoryBuilder<DefaultClientModel>(new ProxyGenerator());
>             Parallel.For(0, 1000, x => builder.CreateChannelFactory<ChannelFactory<IOperations>>(new DefaultClientModel().WithoutAsyncCapability()));
>         }
>
>         [Test]
>         public void Will_not_throw_mixed_contract()
>         {
>             var builder = new AsynChannelFactoryBuilder<DefaultClientModel>(new ProxyGenerator());
>             Parallel.For(0, 1000, x => builder.CreateChannelFactory<ChannelFactory<IOperationsAll>>(new DefaultClientModel()));
>         }
>
>         [Test]
>         public void Will_not_throw_async_only_contract()
>         {
>             var builder = new AsynChannelFactoryBuilder<DefaultClientModel>(new ProxyGenerator());
>             Parallel.For(0, 1000, x => builder.CreateChannelFactory<ChannelFactory<IAsyncOperations>>(new DefaultClientModel()));
>         }
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/castleproject/Windsor/issues/111#issuecomment-227018288>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIhHvjCu_3y7V2tEj4jXFXS7PusE4XNks5qNaU7gaJpZM4GzFIy>
> .
>



-- 
Cheers,
hammett
http://www.d-collab.com/
http://www.hammettblog.com/

**Comment by queil** [comment]
Thanks. No rush though as I've got the workaround described above.

**Comment by NielsSkovgaard** [comment]
Thanks for the workaround, which we have applied now. We have had this problem for months on a project without being able to find out why, until finding this. Is there a way to fix the bug, or should this issue be closed?

**Comment by fir3pho3nixx** [comment]
> Is there a way to fix the bug, or should this issue be closed?

Before we close should we consider updating docs?

**Comment by Liwoj** [comment]
Long time Windsor user here. WCF facility seems very useful but I really don't understand the context why was the capability to generate async operations over the sync only interface was introduced. I mean today the tooling (be it VS or svcutil) has the capability of generating async Task based methods. Why would anyone want to generate a proxy that has old style "BeginWcfCall" pattern implemented ?

So maybe to solve this issue it would be easier to just remove this obsoleted feature?
