### ISSUE TITLE
Possible bug for default type naming convention

### ISSUE THREAD

**Issue by MaorBM** [castleproject/Windsor#129]
When registering two different types from different assemblies but with the same full name a ComponentRegistrationException is thrown:
```
container.Register(
                Component.For<ATest>().ImplementedBy<LIB1.NamespaceName.Class1>().LifestyleSingleton(),
                Component.For<ATest>().ImplementedBy<LIB2.NamespaceName.Class1>().LifestyleSingleton());

```
Where LIB1 and LIB2 are aliases for the two assemblies.
I assume that every registered type is stored with the
 TypeFullName as the key. Maybe the type's AssemblyQualifiedName should be the key.
See attached solution for example.
[CastleTests.zip](https://github.com/castleproject/Windsor/files/238228/CastleTests.zip)

**Comment by jonorossi** [comment]
@MaorBM I tried downloading your attached solution, GitHub returns a 404. Could you please also include the full `ComponentRegistrationException` description and stack trace. Thanks.

**Comment by MaorBM** [comment]
Hi,
The received exception information.
I’ve uploaded [here](http://tempsend.com/74B05D7B4C) the source code as well in case you still need it.

Exception Message:
“ Component CastleTestsLibrary.Class1 could not be registered. There is already a component with that name. Did you want to modify the existing component instead? If not, make sure you specify a unique name.”
Exception StackTrace:
“   at Castle.MicroKernel.SubSystems.Naming.DefaultNamingSubSystem.Register(IHandler handler)
   at Castle.MicroKernel.DefaultKernel.AddCustomComponent(ComponentModel model)
   at Castle.MicroKernel.Registration.ComponentRegistration`1.Castle.MicroKernel.Registration.IRegistration.Register(IKernelInternal kernel)
   at Castle.MicroKernel.DefaultKernel.Register(IRegistration[] registrations)
   at Castle.Windsor.WindsorContainer.Register(IRegistration[] registrations)
   at CastleTests.Program.Main(String[] args) in C:\Users\dp26817\Projects\ToDelete\CastleTests\CastleTests\Program.cs:line 19
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart() “

**Comment by kkozmic** [comment]
This is not a bug. It's an early warning you're about to shoot yourself in the foot.

If you do know what you're doing and are certain you want to proceed just specify the names explicitly as you like.

**Comment by MaorBM** [comment]
I think it is a bug because it seems that the auto naming takes the type's full name rather its AssemblyQualifiedName. The full name is not unique.
You are right that a way to overcome this is to explicitly specify the name, but i belive that if someone relies on the auto naming feature, he does not expect to catch an exception for two completely different types (event if they have the same name and namespace).

**Comment by kkozmic** [comment]
Again, what it does was a deliberate decision. I don't think it should be changed.

**Comment by MaorBM** [comment]
oh OK Sorry i was just pointing it, I didn't know that this was the intention in the first place (hence the "possible" :) ).
Thanks.

**Comment by kkozmic** [comment]
No worries ;)

The reason why it behaves that way is that in most cases this really is a bug, for example you're trying to load two versions of the same assembly.

There's very few scenarios where having two types with the same name is desired.
