### ISSUE TITLE
Master build is broken: error NU1603

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Windsor#321]
No code has changed but the build is broken, the master Castle Core build isn't broken (even after I reran it too).

```
NUnit.Engine.NUnitEngineException: The path specified in --result src\Castle.Windsor.Tests\bin\Release\net45\TestResult_Windsor.xml could not be written to ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\projects\windsor\src\Castle.Windsor.Tests\bin\Release\net45\TestResult_Windsor.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at NUnit.Engine.Services.NUnit3XmlResultWriter.WriteResultFile(XmlNode resultNode, String outputPath)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   --- End of inner exception stack trace ---
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

**Comment by jonorossi** [comment]
The version of NUnit hadn't changed, it is actually caused by the assembly failing compilation because of this warning (converted to an error by warnings as errors).

> C:\projects\windsor\src\Castle.Windsor\Castle.Windsor.csproj : error NU1603: Castle.Core 4.0.0 depends on System.ComponentModel.TypeConverter (>= 4.0.1) but System.ComponentModel.TypeConverter 4.0.1 was not found. An approximate best match of System.ComponentModel.TypeConverter 4.1.0 was resolved.

I guess the .NET CLI tooling has been updated either by AppVeyor or our build just pulls the latest.

**Comment by jonorossi** [comment]
We'll need to set the required Castle Core to 4.1.0.
