### ISSUE TITLE
First-chance HandlerException thrown for optional parameters

### ISSUE THREAD

**Issue by jnm2** [castleproject/Windsor#449]
It's good practice to minimize exception throwing and handling where possible. First-chance exceptions cause the debugger to break when you're debugging some unrelated issue which requires you to turn off Just My Code. In order to get to the exception or breakpoint you care about, you have to skip through many exceptions you don't care about. It can make an otherwise short series of debugging sessions frustrating, especially if the debugger is a bit sluggish.

This is a regular thorn in the side caused by other libraries as well, including the BCL itself. See `https://github.com/dotnet/corefx/issues/19928#issuecomment-330630112` and lower, for instance.

Culprit:

https://github.com/castleproject/Windsor/blob/09751a40229cc9867e4a16f8c3a23cd92ec87adb/src/Castle.Windsor/MicroKernel/Resolvers/DefaultDependencyResolver.cs#L427-L435

(The `Try` name implies that it is not an exceptional case if the handler cannot be gotten from the kernel, and therefore an exception should not be thrown. Optional parameters are indeed not an exceptional case, so it would be better to follow the `Try` pattern here instead of throwing.)

Repro code that works outside the debugger, suitable for unit testing:

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ExceptionServices;
using Castle.MicroKernel.Registration;
using Castle.Windsor;

public static class Program
{
    public sealed class SomeService
    {
        public SomeService(IEqualityComparer<string> optionalParam = null)
        {
        }
    }

    public static void Main()
    {
        using (var container = new WindsorContainer())
        {
            container.Register(Component.For<SomeService>());

            var service = AssertNoFirstChanceExceptions(() => container.Resolve<SomeService>());

            container.Release(service);
        }
    }

    private static T AssertNoFirstChanceExceptions<T>(Func<T> function)
    {
        T returnValue;
        var firstChanceExceptions = new List<Exception>();

        var handler = new EventHandler<FirstChanceExceptionEventArgs>((sender, e) =>
            firstChanceExceptions.Add(e.Exception));

        AppDomain.CurrentDomain.FirstChanceException += handler;
        try
        {
            returnValue = function.Invoke();
        }
        finally
        {
            AppDomain.CurrentDomain.FirstChanceException -= handler;
        }

        if (firstChanceExceptions.Any())
        {
            Assert.Fail("First-chance exceptions thrown:\r\n\r\n"
                + string.Join("\r\n\r\n", firstChanceExceptions));
        }

        return returnValue;
    }
}
```

**Comment by jnm2** [comment]
I wrote an NUnit test action that fails tests that cause first-chance exceptions and found another place that Windsor is causing and catching exceptions internally.

https://github.com/castleproject/Windsor/blob/6e82f546f0fed467420e61cbdd09fb077f452594/src/Castle.Windsor/Core/Internal/TypeUtil.cs#L72-L89

> //Yeah, this exception is undocumented, yet it does get thrown in some cases (I was unable to reproduce it reliably)
   
I'm getting TypeLoadException every time.


In addition, this is not a first-chance exception in production code, but I discovered that `CreatingContainerTestCase.With_configuration_file_relative` loads `XmlFiles/hasFileIncludes.xml` which has an XML file with an invalid include URI.

```
<configuration>
  <include uri="include1.xml"/>
  <!-- this is also valid -->
  <include uri="file://include2.xml"/>
</configuration>
```xml

```
First-chance exceptions:
System.ArgumentException: Invalid Uri: no scheme delimiter found on XmlFiles/hasFileIncludes.xml
   at Castle.Core.Resource.CustomUri.ParseIdentifier(String identifier)
   at Castle.MicroKernel.SubSystems.Resource.DefaultResourceSubSystem.CreateResource(String resource)
   at Castle.Windsor.WindsorContainer.GetInterpreter(String configurationUri)
```

**Comment by jnm2** [comment]
In addition, this is not a first-chance exception in production code, but I discovered that `CreatingContainerTestCase.With_configuration_file_relative` loads `XmlFiles/hasFileIncludes.xml` which has an XML file with an invalid include URI.

```xml
<configuration>
  <include uri="include1.xml"/>
  <!-- this is also valid -->
  <include uri="file://include2.xml"/>
</configuration>
```

```
First-chance exceptions:
System.ArgumentException: Invalid Uri: no scheme delimiter found on XmlFiles/hasFileIncludes.xml
   at Castle.Core.Resource.CustomUri.ParseIdentifier(String identifier)
   at Castle.MicroKernel.SubSystems.Resource.DefaultResourceSubSystem.CreateResource(String resource)
   at Castle.Windsor.WindsorContainer.GetInterpreter(String configurationUri)
```

Looks like a bad assumption on the part of whoever wrote `hasFileIncludes.xml`? Either that, or this is intended behavior and this too represents a first-chance exception that happens in production code.

**Comment by jnm2** [comment]
Here is the source I'm using to make these tests fail:

##### DetectFirstChanceExceptionsAttribute.cs

<details>

```c#
#if !NETCOREAPP1_0
[assembly: CastleTests.DetectFirstChanceExceptions]

namespace CastleTests
{
	using System;
	using System.Collections.Generic;
	using System.Diagnostics;
	using System.Linq;
	using System.Reflection;
	using System.Runtime.ExceptionServices;
	using System.Text;

	using NUnit.Framework;
	using NUnit.Framework.Constraints;
	using NUnit.Framework.Interfaces;
	using NUnit.Framework.Internal;

	public sealed class DetectFirstChanceExceptionsAttribute : Attribute, ITestAction
	{
		private readonly Dictionary<string, List<Exception>> firstChanceExceptionsByTest = new Dictionary<string, List<Exception>>();

		public void BeforeTest(ITest test)
		{
			firstChanceExceptionsByTest.Add(test.Id, new List<Exception>());
			AppDomain.CurrentDomain.FirstChanceException += CurrentDomain_FirstChanceException;
		}

		public void AfterTest(ITest test)
		{
			AppDomain.CurrentDomain.FirstChanceException -= CurrentDomain_FirstChanceException;

			var firstChanceExceptions = firstChanceExceptionsByTest[test.Id];
			firstChanceExceptionsByTest.Remove(test.Id);

			if (firstChanceExceptions.Any())
			{
				var message = new StringBuilder();
				for (var i = 0; i < firstChanceExceptions.Count; i++)
				{
					message.Append("First-chance exception ").Append(i + 1).Append(" of ").Append(firstChanceExceptions.Count).AppendLine(":");
					message.AppendLine(firstChanceExceptions[i].ToString());
					message.AppendLine();
				}

				message.Append("Expected: no first-chance exceptions.");

				Assert.Fail(message.ToString());
			}
		}

		// This one can neither be inlined nor can tail call, so it will be in the stack trace if this family of methods is used.
		private static readonly MethodInfo AssertThrowsMethod = typeof(Assert).GetMethod(
			nameof(Assert.Throws),
			BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly,
			null,
			new[] { typeof(IResolveConstraint), typeof(TestDelegate), typeof(string), typeof(object[]) },
			null);

		private void CurrentDomain_FirstChanceException(object sender, FirstChanceExceptionEventArgs e)
		{
			var exceptionTrace = new StackTrace(e.Exception);

			if (exceptionTrace.FrameCount != 0
			    && exceptionTrace.GetFrame(0).GetMethod().DeclaringType?.Assembly == TestExecutionContext.CurrentContext.CurrentTest.TypeInfo.Assembly)
			{
				// Ignore exceptions thrown by methods declared in the test project
				return;
			}

			// exceptionTrace doesn’t go far enough back to include the Assert.Throws method
			var fullTrace = new StackTrace();
			for (var i = 0; i < fullTrace.FrameCount; i++)
			{
				if (fullTrace.GetFrame(i).GetMethod() == AssertThrowsMethod) return;
			}

			firstChanceExceptionsByTest[TestContext.CurrentContext.Test.ID].Add(e.Exception);
		}

		public ActionTargets Targets => ActionTargets.Test;
	}
}
#endif
```

</details>
