### ISSUE TITLE
WindsorContainer crashes with corrupt machine.config

### ISSUE THREAD

**Issue by FramnkRulez** [castleproject/Windsor#528]
This is a strange issue we've encountered on some machine that seem to have corrupted .NET machine.config files.  What happens is that when the WindsorContainer is constructed, it uses the DefaultKernel which has this code in the constructor:

`Logger = new TraceLogger("Castle.Windsor", LoggerLevel.Warn);`

This creates a Castle.Core TraceLogger which throws an exception due to the corrupted machine.config.  Since there is no exception handling around this in DefaultKernel it will cause the whole app to crash (or to fail to construct the container if the exception is caught).

A way to reproduce this is to create a corrupt machine.config file by adding this add the end:

` <system.diagnostics>  
      <sources>  
         <source name="mySource" switchName="sourceSwitch"
            switchType="System.Diagnostics.SourceSwitch" 
            <listeners>  
               <add name="console"
                  type="System.Diagnostics.ConsoleTraceListener" >  
                  <filter type="System.Diagnostics.EventTypeFilter"
                     initializeData="Error" />  
               </add>  
               <remove name="Default" />  
            </listeners>  
         </source>  
      </sources>  
      <switches>  
         <add name="sourceSwitch" value="Warning" />  
      </switches>
   </system.diagnostics>`

After rebooting, attempt to run a .NET app which attempts to create a WindsorContainer and it will crash with the following stack trace:

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.EnsureInit(System.String)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(System.String)
   at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   at System.Diagnostics.DiagnosticsConfiguration.Initialize()
   at System.Diagnostics.DiagnosticsConfiguration.get_Sources()
   at System.Diagnostics.TraceSource.Initialize()
   at Castle.Core.Logging.TraceLogger.IsSourceConfigured(System.Diagnostics.TraceSource)
   at Castle.Core.Logging.TraceLogger.Initialize()
   at Castle.Core.Logging.TraceLogger..ctor(System.String, Castle.Core.Logging.LoggerLevel)
   at Castle.MicroKernel.DefaultKernel..ctor(Castle.MicroKernel.IDependencyResolver, Castle.MicroKernel.IProxyFactory)
   at Castle.MicroKernel.DefaultKernel..ctor()
   at Castle.Windsor.WindsorContainer..ctor()

Granted this is a bad scenario but I've artificially produced this stack trace based on some error reports we are getting where the cause is unclear (and we can't really control a user's machine.config).

**Comment by generik0** [comment]
@FramnkRulez please provide a sample project for replication
