### ISSUE TITLE
Extensions.DependencyInjection: KestrelServer unable to instantiate for https

### ISSUE THREAD

**Issue by robertcoltheart** [castleproject/Windsor#549]
```
System.AggregateException: One or more errors occurred. (ComponentActivator: could not instantiate Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer)
 ---> Castle.MicroKernel.ComponentActivator.ComponentActivatorException: ComponentActivator: could not instantiate Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer
 ---> System.Exception: Could not instantiate Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.EnsureDefaultCert()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.ApplyDefaultCert(HttpsConnectionAdapterOptions httpsOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
```

Using the solution here seems to solve the issue: https://github.com/volosoft/castle-windsor-ms-adapter/pull/21

**Comment by robertcoltheart** [comment]
I don't think this is an issue necessarily, I seemed to have resolved it somehow.
