### ISSUE TITLE
Double generic service where one generic parameter is generic itself and has type constraints

### ISSUE THREAD

**Issue by sqeezy** [castleproject/Windsor#598]
Today I stumbled over this issue in a day job project. I`m not sure whether I miss something obvious.
The resolve seems to misinterpret the origin of the generic type constraint. I would be happy to help solve this issue, but I would need a bit of finger pointing.

```csharp
	public interface IDoubleGeneric<TOne,TTwo> {   }
	public class Foo<T> : IDoubleGeneric<T, IGenericTypeWithConstraint<T>> where T : class {   }

	public interface IGenericTypeWithConstraint<T> where T : class {   }

        [Test]
        public void Implementation_with_single_generic_parameter_that_is_used_in_double_generic()
        {
	        Container.Register(
		        Component.For(typeof(IDoubleGeneric<,>))
			        .ImplementedBy(typeof(Foo<>)));
        
	        var instance = Container.Resolve<IDoubleGeneric<object, IGenericTypeWithConstraint<object>>>();
	        IDoubleGeneric<object, IGenericTypeWithConstraint<object>> manualInstance = new Foo<object>();
        
	        Assert.IsInstanceOf<IDoubleGeneric<object, IGenericTypeWithConstraint<object>>>(instance);
        }
```

The test fails with:

```
Castle.MicroKernel.Handlers.GenericHandlerTypeMismatchException : Types System.Object, CastleTests.IGenericTypeWithConstraint`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] don't satisfy generic constraints of implementation type CastleTests.Foo`1 of component 'CastleTests.Foo`1'. This is most likely a bug in your code.
   at Castle.MicroKernel.Handlers.DefaultGenericHandler.GetClosedImplementationType(CreationContext context, Boolean instanceRequired) in C:\Users\anton.herzog\Github\Windsor\src\Castle.Windsor\MicroKernel\Handlers\DefaultGenericHandler.cs:line 364
   at Castle.MicroKernel.Handlers.DefaultGenericHandler.Resolve(CreationContext context, Boolean instanceRequired) in C:\Users\anton.herzog\Github\Windsor\src\Castle.Windsor\MicroKernel\Handlers\DefaultGenericHandler.cs:line 184
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context) in C:\Users\anton.herzog\Github\Windsor\src\Castle.Windsor\MicroKernel\Handlers\AbstractHandler.cs:line 181
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, Arguments additionalArguments, IReleasePolicy policy, Boolean ignoreParentContext) in C:\Users\anton.herzog\Github\Windsor\src\Castle.Windsor\MicroKernel\DefaultKernel.cs:line 751
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, Arguments arguments, IReleasePolicy policy, Boolean ignoreParentContext) in C:\Users\anton.herzog\Github\Windsor\src\Castle.Windsor\MicroKernel\DefaultKernel_Resolve.cs:line 185
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, Arguments arguments) in C:\Users\anton.herzog\Github\Windsor\src\Castle.Windsor\MicroKernel\DefaultKernel_Resolve.cs:line 112
   at Castle.Windsor.WindsorContainer.Resolve[T]() in C:\Users\anton.herzog\Github\Windsor\src\Castle.Windsor\Windsor\WindsorContainer.cs:line 596
   at CastleTests.NestedGenericsTestCase.Implementation_with_single_generic_parameter_that_is_used_in_double_generic() in C:\Users\anton.herzog\Github\Windsor\src\Castle.Windsor.Tests\NestedGenericsTestCase.cs:line 33
```

**Comment by rvdginste** [comment]
I didn't test your code, and I don't know whether this could work for you... but would this issue be resolved by introducing a generic `IFoo<T>` interface as follows?
```
public interface IDoubleGeneric<TOne,TTwo> { }
public interface IFoo<T> : IDoubleGeneric<T, IGenericTypeWithConstraint<T>> where T : class { }
public class Foo<T> : IFoo<T> where T : class { }

```
And the registration code based on `IFoo<T>`
```
Container.Register(
  Component.For(typeof(IFoo<>))
    .ImplementedBy(typeof(Foo<>)));
```
If you introduce that interface,every possible resolve for that interface with one generic parameter can be satisfied with the given registration. I think your current registration is too general and not every instance of the interface could be resolved with the implementation registered, that is likely why the code fails.

**Comment by rvdginste** [comment]
Otherwise, you might check `IGenericImplementationMatchingStrategy` and `IGenericServiceStrategy`.

**Comment by sqeezy** [comment]
Thank you for your hint. On the face of it this solves all my issues.
